package loops;

public class WhileLoop {
    public static void main(String[] args) {
        //to do autogenerated method stub
        int  i =0;
        System.out.println("Even numbers from 1 to 10 are\n");
        while(i<=10){
            System.out.println(i);
            i = i+2;
        }


    }
    
}
